In [1]:
import pandas as pd

df = pd.read_csv("/home/bs_thesis/Desktop/Rushi/BS_thesis/Survey on English Languages Diffculties in Telugu States.csv")

df = df.drop("Timestamp", axis=1)
df

,Age group,Gender,Medium of School,How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?",How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?,How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?,How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?,"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?",How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?,"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?",How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?
0,15-19,Male,English medium,2,5,3,2,4,1,2,1,2,1,4,4,4,3
1,20-25,Female,English medium,2,3,1,2,3,1,3,1,1,1,2,3,2,2
2,20-25,Male,English medium,1,1,1,1,1,1,1,1,5,5,4,4,4,5
3,20-25,Male,English medium,1,4,1,1,3,1,2,1,2,1,4,4,4,3
4,20-25,Male,English medium,1,4,3,1,1,1,2,1,2,1,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,15-19,Female,Both,2,1,2,4,2,4,2,2,1,1,1,1,2,4
479,15-19,Female,English medium,2,3,1,2,1,2,3,4,3,2,4,5,5,3
480,15-19,Female,Both,3,4,2,2,3,2,4,2,1,2,4,2,3,1
481,15-19,Female,English medium,3,3,2,5,2,2,3,4,5,4,3,2,4,1
482,15-19,Female,English medium,3,2,1,3,2,4,4,4,4,3,3,3,3,4

In [2]:
df = df.rename(columns={
"How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Conv_diff",

"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?":"Speak_diff",

"How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?": "Write_diff",

"How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Read_diff",

"How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?": "MT_influence",

"How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?": "Lect_diff",

"How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?": "Movie_Nosub",

"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?": "Movie_sub",

"How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?":"Learning_feel",

"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?":"Switch_diff",

"How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"work_india",

"How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Work_abroad",

"How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Study_other",

"How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Friend_diff"})

In [3]:
df

,Age group,Gender,Medium of School,Conv_diff,Speak_diff,Write_diff,Read_diff,MT_influence,Lect_diff,Movie_Nosub,Movie_sub,Learning_feel,Switch_diff,work_india,Work_abroad,Study_other,Friend_diff
0,15-19,Male,English medium,2,5,3,2,4,1,2,1,2,1,4,4,4,3
1,20-25,Female,English medium,2,3,1,2,3,1,3,1,1,1,2,3,2,2
2,20-25,Male,English medium,1,1,1,1,1,1,1,1,5,5,4,4,4,5
3,20-25,Male,English medium,1,4,1,1,3,1,2,1,2,1,4,4,4,3
4,20-25,Male,English medium,1,4,3,1,1,1,2,1,2,1,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,15-19,Female,Both,2,1,2,4,2,4,2,2,1,1,1,1,2,4
479,15-19,Female,English medium,2,3,1,2,1,2,3,4,3,2,4,5,5,3
480,15-19,Female,Both,3,4,2,2,3,2,4,2,1,2,4,2,3,1
481,15-19,Female,English medium,3,3,2,5,2,2,3,4,5,4,3,2,4,1
482,15-19,Female,English medium,3,2,1,3,2,4,4,4,4,3,3,3,3,4

In [4]:
core_skills = [
    "Conv_diff",   
    "Speak_diff",
    "Write_diff",
    "Read_diff",
    "Lect_diff"
]

In [5]:
summary = df[core_skills].mean().sort_values(ascending=False)
print(summary)

Speak_diff    2.511387
Lect_diff     2.293996
Write_diff    2.175983
Read_diff     2.155280
Conv_diff     2.109731
dtype: float64

In [6]:
text_data = "The analysis of student difficulties in English language skills shows that "

for i, (col, val) in enumerate(summary.items()):
    skill = col.replace("_diff", "").capitalize()
    
    if i == 0:
        text_data += f"{skill} is the most difficult skill with an average score of {val:.2f}. "
    else:
        text_data += f"{skill} has an average difficulty score of {val:.2f}. "

print(text_data)

The analysis of student difficulties in English language skills shows that Speak is the most difficult skill with an average score of 2.51. Lect has an average difficulty score of 2.29. Write has an average difficulty score of 2.18. Read has an average difficulty score of 2.16. Conv has an average difficulty score of 2.11.

In [7]:
prompt = f"""
Analyze the following data:

{text_data}


1. Rank the skills from most to least difficult.
2. What overall learning pattern do you observe?
3. Do students struggle more with communication or comprehension skills?
4. What major challenges do students face?
5. What factors contribute to these difficulties?
6. Provide 2–3 key insights.
7. Identify any surprising trends.
8. What improvements would you suggest for students?
"""

In [ ]:
from groq import Groq
client = Groq(api_key="API_CODE_HERE")

chat = client.chat.completions.create(
    model="llama-3.1-8b-instant", 
    messages=[{"role": "user", "content": prompt}]
)

In [9]:
print(chat.choices[0].message.content)

Based on the provided data, here are the analyses to the asked questions:

1. **Rank the skills from most to least difficult:**

   - Speak: 2.51 (Most difficult)
   - Lect: 2.29
   - Write: 2.18
   - Read: 2.16
   - Conv: 2.11 (Least difficult)

2. **What overall learning pattern do you observe?**

   From the data, we can observe that students generally face more difficulty with speaking and listening skills (Speak and Lect) compared to reading and writing skills (Read and Write). The Conv (conversation) skill falls somewhere in between, indicating a moderate level of difficulty.

3. **Do students struggle more with communication or comprehension skills?**

   Based on the rankings, it appears that students tend to struggle more with communication skills (Speak and Lect) than comprehension skills (Read and Write). However, Conv, which combines aspects of communication and comprehension, falls in the middle. This may indicate that the distinction is not entirely clear-cut.

4. **What major challenges do students face?**

   Students face major challenges when trying to master English language speaking and listening skills, particularly in a formal setting (Lect).

5. **What factors contribute to these difficulties?**

   There are a few possible factors that may contribute to these difficulties:
   - Language proficiency: Students may not have mastered the nuances of English pronunciation or grammar that are specific to speaking and listening.
   - Cultural differences: Students from non-English speaking backgrounds may have varying degrees of familiarity with the cultural context in which English is typically used.
   - Limited practice opportunities: Students may not have enough opportunities to practice speaking and listening in English, which can hinder their development of these skills.

6. **Provide 2–3 key insights:**

   - English language speaking and listening skills are the most challenging for students to master.
   - Students tend to struggle more with formal speaking and listening situations (Lect).
   - The difficulty levels decrease as we move from speaking and listening (Speak and Lect) to comprehension skills (Read and Conv).

7. **Identify any surprising trends:**

   The surprising trend here is the significant difficulty that students face with speaking, given that it's a skill that can be practiced regularly in everyday conversations. However, it may not be as straightforward when trying to apply formal speaking and listening skills in academic or professional settings.

8. **What improvements would you suggest for students?**

   - Regular practice: Engage in regular conversations with native speakers, either in person or online, to improve speaking and listening skills.
   - Focus on listening and speaking in formal settings: Pay particular attention to mastering formal speaking and listening skills by listening to lectures or watching videos related to academic or professional topics.
   - Seek feedback: Ask teachers, peers, or native speakers to provide feedback on pronunciation, grammar, and vocabulary usage.

In [ ]:
from groq import Groq
client = Groq(api_key= "API_CODE_HERE")

chat = client.chat.completions.create(
    model="llama-3.3-70b-versatile", 
    messages=[{"role": "user", "content": prompt}]
)

In [11]:
print(chat.choices[0].message.content)

**1. Rank the skills from most to least difficult:**

Based on the average difficulty scores, the ranking from most to least difficult is:

1. Speak (2.51)
2. Lect (2.29)
3. Write (2.18)
4. Read (2.16)
5. Conv (2.11)

**2. What overall learning pattern do you observe:**

The overall learning pattern suggests that students struggle more with productive skills (Speak and Write) than receptive skills (Read and Lect). Additionally, Conversational skills (Conv) appear to be relatively less challenging.

**3. Do students struggle more with communication or comprehension skills:**

Students seem to struggle more with communication skills, particularly Speaking, which has the highest average difficulty score. This indicates that students may find it more challenging to express themselves effectively in English, rather than understanding written or spoken English.

**4. What major challenges do students face:**

The major challenges students face appear to be related to speaking and communicative skills, which require more active participation and production of language. This may be due to factors such as lack of practice, limited exposure to authentic language, or difficulties with pronunciation, vocabulary, and grammar.

**5. What factors contribute to these difficulties:**

Several factors may contribute to these difficulties, including:

* Limited opportunities for authentic language practice
* Insufficient feedback on speaking and writing skills
* Difficulty with pronunciation, vocabulary, and grammar
* Cultural or language background differences
* Learning style or strategy differences

**6. Provide 2–3 key insights:**

1. Speaking skills are the most challenging for students, indicating a need for more focused practice and feedback in this area.
2. Students may benefit from more authentic language practice and exposure to real-life communication scenarios.
3. Receptive skills (Reading and Lecturing) appear to be relatively less challenging, suggesting that students may have a stronger foundation in comprehension skills.

**7. Identify any surprising trends:**

One surprising trend is that Lecturing (presumably listening to lectures) has a higher average difficulty score than Reading. This may indicate that students struggle with the pace, vocabulary, or accents used in lectures, which could be an area for further support.

**8. What improvements would you suggest for students:**

To improve their English language skills, students could:

* Engage in regular speaking and conversation practice with peers or language exchange partners
* Seek feedback on their speaking and writing skills from instructors or mentors
* Practice active listening and note-taking skills to improve comprehension
* Use authentic materials (e.g., podcasts, videos, news articles) to practice reading and listening skills
* Develop strategies for managing language learning challenges, such as using language learning apps or seeking support from language tutors.